# Generated by Django 4.2.6 on 2023-10-29 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("sku", models.CharField(max_length=50)),
                ("barcode", models.CharField(max_length=50)),
                ("brand", models.CharField(max_length=50)),
                ("category", models.CharField(max_length=50)),
                ("unit", models.CharField(max_length=50)),
                ("current_stock", models.IntegerField()),
                ("minimum_stock", models.IntegerField()),
                ("maximum_stock", models.IntegerField()),
                ("reorder_quantity", models.IntegerField()),
                ("stock_status", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=50)),
                ("selling_price", models.FloatField()),
                ("cost_price", models.FloatField()),
                ("profit_margin", models.FloatField()),
                ("special_discounts", models.FloatField()),
                ("supplier_name", models.CharField(max_length=100)),
                ("supplier_contact", models.CharField(max_length=100)),
                ("supplier_code", models.CharField(max_length=50)),
                ("lead_time", models.IntegerField()),
            ],
        ),
    ]
