# Generated by Django 4.2.6 on 2023-11-03 05:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ALLInventory", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Product",
        ),
    ]
